---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis-app-pod-deploy
 labels:
  name: redis-app-pod-deploy
  app: demo-voting-app
spec:
 replicas: 1
 selector:
  matchlabels:
    name: redis-app-deploy
    app: demo-voting-app
 template:
   metadata:
    name: redis-app-deploy
    labels:
    app: demo-voting-app 
   spec:
    containers:
    name: redisdeploycont
    image: redis
    ports:
    - containerPort: 6379

