---
apiVersion: v1
kind: Service
metadata:
 name: voting-service
labels:
 name: voting-service
 app: demo-voting-type
spec:
 type: LoadBalancer
 selector: 
  name: voting-app-pod
  app: demo-voting-app
ports:
 - port: 80
   targetport: 80
  